
[build]
  command = "npm run build"
  publish = "public"


[[redirects]]
  from = "/"
  to = "/en"
  status = 301
  force = true
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/es"
  status = 301
  force = true

[functions]
  directory = "netlify/functions"