backend:
  name: git-gateway
  branch: main
media_folder: "public/assets"
public_folder: "/assets"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Etiquetas", name: "tags", widget: "list", default: ["post"] }
      - { label: "Imagen principal", name: "image", widget: "image" }
      - { label: "Descripción de la imagen", name: "imageAlt", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
  - name: "work"
    label: "Work"
    folder: "src/work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título del proyecto", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Clase para el body", name: "bodyClass", widget: "string", default: "nombre__cliente oscuro" }
      - { label: "Estilo para color de fondo", name: "bgcolor", widget: "string", default: "'style= background-color:#e0e5ed;'" }
      - { label: "Estilo para color de textos", name: "textcolor", widget: "string", default: "'style= color:#ea4100;'" }
      - { label: "Categorías", name: "tags", widget: "list", default: ["work"] }
      - { label: "Imagen thumb", name: "thumbnail", widget: "image" }
      - { label: "Descripción en thumb", name: "description", widget: "string" }
      - { label: "Sector", name: "sector", widget: "string" }
      - { label: "Descripción general", name: "basics", widget: "text" }
      - { label: "Imagen de cabecera", name: "image1", widget: "image" }
      - { label: "Plazo de elaboración", name: "year", widget: "string" }
      - { label: "El reto", name: "issue", widget: "text" }
      - { label: "Imagen posterior", name: "image2", widget: "image" }
      - { label: "Servicios", name: "services", widget: "list", default: ["Estrategia de posicionamiento", "Rediseño de logo", "Identidad Corporativa", "Desarrollo de sitio Web"] }
      - { label: "La solución", name: "solution", widget: "text" }
      - { label: "Imágenes subsecuentes", name: "body", widget: "markdown" }