backend:
  name: marker-backend
  branch: main
media_folder: "public/assets"
public_folder: "/assets"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Etiquetas", name: "tags", widget: "list", default: ["post"] }
      - { label: "Imagen principal", name: "image", widget: "image" }
      - { label: "Descripción de la imagen", name: "imageAlt", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
  - name: "work"
    label: "Work"
    folder: "src/work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Etiquetas", name: "tags", widget: "list", default: ["post"] }
      - { label: "Imagen principal", name: "image", widget: "image" }
      - { label: "Descripción de la imagen", name: "imageAlt", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }